language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
      - clang-6.0

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DJET_LIVE_BUILD_TESTS=ON ..
  - make
  - ../tools/tests/test_runner.py -b . -s ../tests/src/

