language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      dist: xenial
      addons:
        apt:
          packages:
            - clang-7
            - lld-7
      env:
        - CC=clang-7
        - CXX=clang++-7
        - CC_FOR_BUILD=clang-7
        - CXX_FOR_BUILD=clang++-7
        - LD=lld-7
    - os: linux
      compiler: gcc
      dist: xenial
      env:
        - CC=gcc
        - CXX=g++
        - CC_FOR_BUILD=gcc
        - CXX_FOR_BUILD=g++
        - LD=ld
    - os: osx
      compiler: clang

before_install:
  - curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq

script:
  - if [ "$LD" == "lld-7" ]; then sudo mv /usr/bin/ld /usr/bin/ld.old && sudo ln -s /usr/bin/lld-7 /usr/bin/ld; fi
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DJET_LIVE_BUILD_TESTS=ON ..
  - make -j4
  - ../tools/tests/test_runner.py -b . -s ../tests/src/

