language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      dist: xenial
      addons:
        apt:
          packages:
            - clang-6.0
            - lld-6.0
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0
        - CC_FOR_BUILD=clang-6.0
        - CXX_FOR_BUILD=clang++-6.0
        - LD=lld-6.0
    - os: linux
      compiler: gcc
      dist: xenial
      env:
        - CC=gcc
        - CXX=g++
        - CC_FOR_BUILD=gcc
        - CXX_FOR_BUILD=g++
        - LD=ld
    - os: osx
      compiler: clang

script:
  - if [ "$LD" == "lld-6.0" ]; then sudo mv /usr/bin/ld /usr/bin/ld.old && sudo ln -s /usr/bin/lld-6.0 /usr/bin/ld; fi
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DJET_LIVE_BUILD_TESTS=ON ..
  - make -j4
  - ../tools/tests/test_runner.py -b . -s ../tests/src/

