language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
      - clang-6.0

script:
  - mkdir build && cd build
  - cmake ..
  - make

